item84-프로그램의_동작을_스레드_스케줄러에_기대지_말라
effective-java-study-with-business/effective-java pull request #79
Opened 2024-02-13 10:28 UTC by dudtjr0831

# 아이템 84. 프로그램의 동작을 스레드 스케줄러에 기대지 말라

정확성이나 성능이 스레드 스케줄러에 따라 달라지는 프로그램이라면 다른 플랫폼에 이식하기 어렵다

## 좋은 프로그램을 만드는 방법

### 프로세스 수를 고려하여 적절한 스레드로 유지
1. 실행 가능한 스레드의 평균적인 수를 프로세서 수보다 지나치게 많아지지 않도록 한다.
-> 스케줄러가 고민할 거리가 줄어든다.
2. 실행준비가 된 스레드들은 맡은 작업을 완료할 때까지 계속 실행되도록 만든다.
-> 스케줄링 정책이 아주 상이한 시스템에서도 동작이 크게 달라지지 않는다.

### 실행 가능한 스레드 수를 적게 유지한다.
1. 다음 일거리가 생길 때까지 대기하도록한다. 단, 스레드는 당장 처리해야 할 작업이 없다면 실행해서는 안 된다.
2. 작업이 너무 짧으면 작업을 분배하는 부담이 오히려 성능을 떨어뜨릴 수 있다.

### Busy Waiting 상태가 되면 안된다.

```java
public void await() {
	while (true) {    // 계속해서 조건을 충족하는지 검사
    	synchornized(this) {
        	if (count == 0) return;
        }
    }
}
```
공유 객체의 상태가 바뀔 때까지 쉬지 않고 검사해서는 안 된다는 뜻이다.
busy waiting은 스레드 스케줄러의 변덕에 취약할 뿐아니라, 프로세서에 큰 부담을 주어 다른 유용한 작업이 실행 될 기회를 박탈한다.

## CPU시간을 충분히 얻지 못하는 프로그램이라도 Thread.yield 사용 금지

```java
public void run() {
    while(true) {
        if(work) {
            //Thread 작업 내용
        } else {
            Thread.yield();
        }
    }
}
```
Thread.yield  : JVM의 Thread Scheduler에게 현재 스레드의 우선 순위를 낮춰도 된다는 힌트를 보내는 메서드

말그대로 힌트만 주는 메서드이기 때문에 확실히 우선순위가 변동된다는 보장도 없고, 테스트할 수단도 없으니
차라리 어플리케이션 구조를 바꿔 동시에 실행 가능한 스레드 수가 적어지도록 조치하자

## 요약
1. 프로그램 동작을 스레드 스케줄러에 기대지 말자.
2. Thread.yield와 스레드 우선순위에 의존해서도 안된다. 힌트일 뿐

2024-02-14 12:18 UTC, JJong0416 requested changes

2024-02-14 12:18 UTC, JJong0416 commented on 10장/item71-필요_없는_검사_예외_사용은_피하라.md
> +# 아이템 71. 필요 없는 검사 예외 사용은 피하라
역머지 후 approve 머지해주세요!

2024-02-14 12:23 UTC, 132262B commented
프로세스 수를 고려하여 적절한 스레드로 유지에 적절한 스레드 수 가 어떻게 계산해야 하는지 궁금합니다.

2024-02-14 12:24 UTC, JJong0416 commented on 10장/item71-필요_없는_검사_예외_사용은_피하라.md
> +# 아이템 71. 필요 없는 검사 예외 사용은 피하라
스핀락, 뮤텍스, block-wakeup 에 대해서 추가해주세요!

2024-02-14 13:28 UTC, 132262B approved these changes

2024-02-18 07:41 UTC, dudtjr0831 commented on 10장/item71-필요_없는_검사_예외_사용은_피하라.md
> +# 아이템 71. 필요 없는 검사 예외 사용은 피하라
추가 했습니다~:)

2024-02-18 07:51 UTC, dudtjr0831 commented
@132262B 

적정 스레드 풀 크기 공식은 다음과 같습니다.
![image](https://github.com/effective-java-study-with-business/effective-java/assets/70935170/01f70aad-e63b-4d56-b3e1-a1acc2d3206d)

해당 공식을 이용하여 어플리케이션을 제작하였을 시 성능 테스트 방법에서 리틀의 법칙을 사용하게 됩니다.

리틀의 법칙: 쓰레드의 개수가 지연시간이나 처리량(시스템이 처리 가능한 처리량)에 미치는 영향을 계산할 수 있는 방법

L = λ * W

L : 동시에 처리되는 요청의 개수
λ  : 시스템이 처리 가능한 평균 처리량
W : 평균 요청 처리 시간

출처: https://code-lab1.tistory.com/269 [코드 연구소:티스토리]

2024-02-25 07:29 UTC, JJong0416 approved these changes

2024-02-27 01:30 UTC, laughcryrepeat approved these changes

2024-03-06 05:27 UTC, minahshin approved these changes

2024-03-06 14:48 UTC, merged