Dudtjr0831
effective-java-study-with-business/effective-java pull request #8
Opened 2023-10-28 13:20 UTC by dudtjr0831

# 아이템 6. 불필요한 객체 생성을 피하라

같은 기능의 객체를 매번 생성하기보다는 객체 하나를 재사용하는 편이 더 빠르고 세련되었다.

## 문자열 생성

쓰면 안되는 예
```java
String s = new String("bikini");
```
다음 문장은 실행이 될 때마다 String 인스턴스를 새로 만든다.

올바른 예시
```java
String s = "bikini";
```
하나의 String 인스턴스를 사용하므로 효율적이다.

## 정적 팩터리 메서드를 사용

```java
boolean b = new Boolean(String); //자바 9 이상 자제 'Boolean(java.lang.String)' is deprecated and marked for remova
boolean b = Boolean.valueOf(String);
```
생성자 대신 정적 팩터리 메서드를 제공하는 불변 클래스에서는 정적 팩터리 메서드를 사용해 불필요한 객체 생성을 피할 수 있다.

## 비싼 객체

생성비용이 비싼 객체가 반복해서 필요하다면 캐싱하여 재사용하길 권한다. 

문자열이 유효한 로마 숫자인지 정규표현식으로 판별하는 메서드이다.
```java
static boolean isRomanNumeral(String s) {
    return s.matches("^(?=.)M*(C[MD]|D?C{0,3})(X[CL]|L?X{0,3})(I[XV]|V?I{0,3})$");
}
```

String.matches는 가장 쉽게 정규 표현식에 매치가 되는지 확인하는 방법이긴 하지만 성능이 중요한 상황에서 반복적으로 사용하기에 적절하지 않다.

matches내부
```java
public boolean matches(String regex) {
        return Pattern.matches(regex, this);
    }
```

즉, 다음과 같이 불변 Pattern 인스턴스 초기화 과정을 거쳐 직접 생성하여 나중에 재사용하게 해야한다.
```java
public class RomanNumber {

    private static final Pattern ROMAN = Pattern.compile("^(?=.)M*(C[MD]|D?C{0,3})(X[CL]|L?X{0,3})(I[XV]|V?I{0,3})$");

    static boolean isRomanNumeral(String s) {
        return ROMAN.matcher(s).matches();
    }

}
```
성능이 개선되고, 코드도 명확해지며, 행위의 의미가 잘 드러난다.

하지만, isRomanNumeral에서 클래스가 초기화 된 후 이 메서드를 한번도 호출하지 않는다면 ROMAN은 쓸데없이 초기화된 꼴이다. "지연초기화"로 불필요한 초기화를 없앨 수는 있지만, 코드를 복잡하게 만들고 성능은 크게 개선되지 않기 때문이다.

(지연초기화 : 필드의 초기화 시점을 그 값이 처음 필요할 때까지 늦추는 기법)

## 어댑터(View)

실제 작업은 뒷단 객체에 위임하고, 자신은 제 2의 인터페이스 역할을 해주는 객체이다. 즉, 뒷단 객체 외에는 관리할 상태가 없으므로 뒷단 객체 하나당 어댑터 하나씩만 만들어지면 충분하다.

Map의 keySet() 메서드는 키를 담은 Set 어댑터(뷰)를 호출한다. 
```java
public class Main {
    public static void main(String[] args) {

        Map<String,String> map = new HashMap<>();

        map.put("java","");
        map.put("c","");

        Set<String> set1 = map.keySet();
        Set<String> set2 = map.keySet();

        System.out.println(set1.size()); //  => 2
        System.out.println(set2.size()); // = > 2

        map.remove("c");
        System.out.println(set1.size()); //  => 1
        System.out.println(set2.size()); //  => 1
    }
}
```

## 오토박싱
프로그래머가 기본 타입과 박싱된 기본 타입을 섞어 쓸 때 자동으로 상호 변환해주는 기술이다.

```java
public class Main {
     public static void main(String[] args) {
        Long sum = 0L;
        for (long i = 0 ; i <= Integer.MAX_VALUE ; i++) {
            sum += i;
        }
        System.out.println(sum);
    }
}
```
위 코드는 불필요한  불변Long 객체에 long형 i를 계속 더하게 되므로 불필요한 Long 인스턴스가 약 2의 31 제곱개 생성된다.
박싱된 타입보다는 기본타입을 사용하고, 의도치 않은 오토박싱이 숨어들지 않도록 주의하자.

## 주의
무거운 객체가 아닌 단순 객체 생성을 피하고자 풀(pool)을 만들지는 말자! 다만 비용이 비싸 재사용이 필요한 DB같은 경우는 제외
-> 코드를 햇갈리게 만들고, 메모리 사용량을 늘리고 성능을 떨어트린다.

2023-10-29 09:06 UTC, JJong0416 requested changes

2023-10-29 09:06 UTC, JJong0416 commented on 2장/item06 - 불필요한 객체 생성을 피하라
> +```
@dudtjr0831 님 안녕하세요 :D
글 너무 잘 읽었습니다. 이쪽 부분에서 궁금한 점이 있는데,
왜 리터럴로 선언안하고 new 키워드를 사용하면 안좋은 예시인가요?

2023-10-29 09:06 UTC, JJong0416 commented on 2장/item06 - 불필요한 객체 생성을 피하라
> +```
스프링 내부에서 matches를 쓰는 부분이 대표적으로 어디 있나요!?

2023-10-30 04:24 UTC, dudtjr0831 commented on 2장/item06 - 불필요한 객체 생성을 피하라
> +```
안녕하세요!

        String s1 = new String("bikini");
        String s2 = new String("bikini");
위와 같이 사용할 경우 s1 과 s2는 다른 값으로 각각 새로운 객체도 생성되고, 메모리가 할당되어 저장되므로 s1==s2는 false입니다!

        String s3 = "bikini"; 
        String s4 = "bikini"; 
하지만 이렇게 사용할 경우 문자열 리터럴을 풀에 저장하고 동일한 문자열 리터럴을 가리키는 모든 문자열 변수는 동일한 문자열 인스턴스를 참조하므로 s3 == s4는 true가 나오게 됩니다!

조금 더 깊게 공부 할 수 있게 해주셔서 감사합니다.

2023-10-30 07:13 UTC, JJong0416 approved these changes

2023-10-30 11:37 UTC, 132262B approved these changes
잘 보고 갑니다.

2023-10-31 04:05 UTC, hbae approved these changes

2023-11-01 12:16 UTC, laughcryrepeat approved these changes

2023-11-04 17:03 UTC, merged